# Generated by Django 5.2.5 on 2025-08-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaocredito',
            name='cor',
            field=models.CharField(choices=[('BLUE', 'Azul'), ('GREEN', 'Verde'), ('RED', 'Vermelho'), ('PURPLE', 'Roxo'), ('BLACK', 'Preto')], default='BLUE', max_length=6, verbose_name='Cor do Cartão'),
        ),
    ]
