# Generated by Django 5.2.5 on 2025-08-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_cartaocredito_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaocredito',
            name='cor',
            field=models.CharField(choices=[('BLUE', 'Azul'), ('GREEN', 'Verde'), ('RED', 'Vermelho'), ('PURPLE', 'Roxo'), ('BLACK', 'Preto'), ('ORANGE', 'Laranja'), ('GRAY', 'Cinza')], default='GRAY', max_length=6, verbose_name='Cor do Cartão'),
        ),
    ]
